### ISSUE TITLE
tvb connectivity

### ISSUE THREAD

**Issue by dokato** [BrainModes/TVB-Pypeline#3]
Is it possible with this pipeline to get the connectivity in the format as it goes to the default the Virtual Brain connectivity function: http://docs.thevirtualbrain.com/api/tvb.datatypes.html?highlight=connectivity#module-tvb.datatypes.connectivity ?

**Comment by BrainModes** [comment]
Yes, the pipeline produces a zip file that can be directly uploaded to TVB.
